name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  say_the_data:
    runs-on: ubuntu-20.04
    steps :
      - name : date
        run  : |
          date
        
        name : ls
        run : | 
          ls
